title: NYQ'INK
description: "A personal blog about experience sharing, reading growth, financial investment and fitness guidance."
author:
  name: "NYQ"
  email: "ningyiqin@gmail.com"
  url: "nyq.ink"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "NYQ"
year : "2022"
